apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/
  - ns.yaml

patchesStrategicMerge:
  - web-deployment-replicas.yaml

secretGenerator:
- name: web
  files:
  - password.txt

configMapGenerator:
- name: web
  literals:
  - COMPANY=SIGHUP
  - SOME_VAR=dev
