namespace: monitoring

bases:
- ../base

configMapGenerator:
- name: prometheus-config
  behavior: merge
  files:
  - prometheus.yml
- name: prometheus-rules
  behavior: merge
  files:
  - record.rules
