apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: kubeprimer-db
  name: kubeprimer-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
