apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: powerapp-backend
  name: powerapp-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: powerapp-backend
    spec:
      containers:
      - name: powerapp-backend
        env:
        - name: MONGO_HOST
          value: powerapp-mongodb-service
        image: sighup/kubeprimer-backend
      restartPolicy: Always
