apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        env:
        - name: MONGO_HOST
          value: mongodb
        image: sighup/kubeprimer-backend
      restartPolicy: Always
