apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: powerapp-mongodb
  name: powerapp-mongodb
spec:
  replicas: 1
  # strategy used to replace old pods by new ones.
  strategy:
    type: Recreate # All existing pods are killed before creating new ones
  template:
    metadata:
      labels:
        app: powerapp-mongodb
      name: powerapp-mongodb
    spec:
      containers:
      - name: powerapp-mongo
        image: mongo:3.7.3
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: db-data
      - name: mongodb-exporter
        image: quay.io/sighup/mongodb_exporter:v0.6.2
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017"
        ports:
        - name: metrics
          containerPort: 9216
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: powerapp-db-volume
