apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: powerapp-web
  name: powerapp-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: powerapp-web
    spec:
      containers:
      - name: powerapp-web
        env:
        - name: BACKEND_HOST
          value: powerapp-backend-service
        - name: COMPANY
          valueFrom:
            configMapKeyRef:
              name: web
              key: COMPANY
        - name: SOME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web
              key: some-password
        image: sighup/kubeprimer-web
        ports:
        - containerPort: 80
      restartPolicy: Always
