apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: powerapp-web
  name: powerapp-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: powerapp-web
    spec:
      containers:
      - name: powerapp-web
        env:
        - name: BACKEND_HOST
          value: powerapp-backend-service
        image: sighup/kubeprimer-web
        ports:
        - containerPort: 80
      restartPolicy: Always
