apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maildev
  name: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
      - name: maildev
        image: djfarrelly/maildev:1.0.0-rc2
        ports:
        - name: http
          containerPort: 1080
        - name: smtp
          containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maildev
  name: maildev-web
spec:
  type: NodePort
  ports:
  - port: 1080
    nodePort: 30080
    targetPort: 1080
  selector:
    app: maildev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maildev
  name: maildev-smtp
spec:
  ports:
  - port: 1025
    targetPort: 1025
  selector:
    app: maildev
