apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9216'
  creationTimestamp: null
  labels:
    app: powerapp-mongodb-service
  name: powerapp-mongodb-service
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
    protocol: TCP
  - name: metrics
    port: 9216
    targetPort: 9216
    protocol: TCP
  selector:
    app: powerapp-mongodb
